import { test, expect } from '@playwright/test';
import { OpenurlPage } from '../pages/openurl-page';
import { TboxWaitPage } from '../pages/tbox-wait-page';
import { WebshopTopMenuPage } from '../pages/webshop-top-menu-page';
import { WebshopLogInPagePage } from '../pages/webshop-log-in-page-page';
import { TboxSetBufferPage } from '../pages/tbox-set-buffer-page';
import { WebshopProductsChoiceTabPage } from '../pages/webshop-products-choice-tab-page';
import { WebshopApparelShoesProductSelectionPage } from '../pages/webshop-apparel-shoes-product-selection-page';
import { WebshopBlueJeansPage } from '../pages/webshop-blue-jeans-page';
import { WebshopShoppingCartPage } from '../pages/webshop-shopping-cart-page';
import { WebshopBillingAddressPage } from '../pages/webshop-billing-address-page';
import { WebshopShippingAddressPage } from '../pages/webshop-shipping-address-page';
import { WebshopShippingMethodPage } from '../pages/webshop-shipping-method-page';
import { WebshopPaymentMethodsPage } from '../pages/webshop-payment-methods-page';
import { WebshopPaymentInformationCreditCardPage } from '../pages/webshop-payment-information-credit-card-page';
import { WebshopConfirmOrderPage } from '../pages/webshop-confirm-order-page';
import { WebshopOrderSuccessfulPage } from '../pages/webshop-order-successful-page';
import { WebshopMyAccountNavigationPage } from '../pages/webshop-my-account-navigation-page';
import { WebshopOrderDetailsPage } from '../pages/webshop-order-details-page';
import { ClosebrowserPage } from '../pages/closebrowser-page';
import { faker } from '@faker-js/faker';
import { format, addMonths, addYears } from 'date-fns';

test.describe('DemoWebShop_Order_Creation|Buiseness Parameters|RTB', () => {
  let openurlPage: OpenurlPage;
  let tboxWaitPage: TboxWaitPage;
  let webshopTopMenuPage: WebshopTopMenuPage;
  let webshopLogInPagePage: WebshopLogInPagePage;
  let tboxSetBufferPage: TboxSetBufferPage;
  let webshopProductsChoiceTabPage: WebshopProductsChoiceTabPage;
  let webshopApparelShoesProductSelectionPage: WebshopApparelShoesProductSelectionPage;
  let webshopBlueJeansPage: WebshopBlueJeansPage;
  let webshopShoppingCartPage: WebshopShoppingCartPage;
  let webshopBillingAddressPage: WebshopBillingAddressPage;
  let webshopShippingAddressPage: WebshopShippingAddressPage;
  let webshopShippingMethodPage: WebshopShippingMethodPage;
  let webshopPaymentMethodsPage: WebshopPaymentMethodsPage;
  let webshopPaymentInformationCreditCardPage: WebshopPaymentInformationCreditCardPage;
  let webshopConfirmOrderPage: WebshopConfirmOrderPage;
  let webshopOrderSuccessfulPage: WebshopOrderSuccessfulPage;
  let webshopMyAccountNavigationPage: WebshopMyAccountNavigationPage;
  let webshopOrderDetailsPage: WebshopOrderDetailsPage;
  let closebrowserPage: ClosebrowserPage;

  let capturedQuantityno: string;
  let capturedPrice: string;
  let capturedOrderNumber: string;
  let captured1: string;

  test.beforeEach(async ({ page }) => {
    openurlPage = new OpenurlPage(page);
    tboxWaitPage = new TboxWaitPage(page);
    webshopTopMenuPage = new WebshopTopMenuPage(page);
    webshopLogInPagePage = new WebshopLogInPagePage(page);
    tboxSetBufferPage = new TboxSetBufferPage(page);
    webshopProductsChoiceTabPage = new WebshopProductsChoiceTabPage(page);
    webshopApparelShoesProductSelectionPage = new WebshopApparelShoesProductSelectionPage(page);
    webshopBlueJeansPage = new WebshopBlueJeansPage(page);
    webshopShoppingCartPage = new WebshopShoppingCartPage(page);
    webshopBillingAddressPage = new WebshopBillingAddressPage(page);
    webshopShippingAddressPage = new WebshopShippingAddressPage(page);
    webshopShippingMethodPage = new WebshopShippingMethodPage(page);
    webshopPaymentMethodsPage = new WebshopPaymentMethodsPage(page);
    webshopPaymentInformationCreditCardPage = new WebshopPaymentInformationCreditCardPage(page);
    webshopConfirmOrderPage = new WebshopConfirmOrderPage(page);
    webshopOrderSuccessfulPage = new WebshopOrderSuccessfulPage(page);
    webshopMyAccountNavigationPage = new WebshopMyAccountNavigationPage(page);
    webshopOrderDetailsPage = new WebshopOrderDetailsPage(page);
    closebrowserPage = new ClosebrowserPage(page);
  });

  test('Create an Order in DemoWebShop with Product Code and Verify Order Details', async ({ page }) => {
    await openurlPage.openURL('https://demowebshop.tricentis.com/');
    await tboxWaitPage.waitForPageLoad();
    await webshopTopMenuPage.clickLoginLink();
    await webshopLogInPagePage.enterEmail('test@example.com');
    await webshopLogInPagePage.enterPassword('Test1234');
    await webshopLogInPagePage.clickLoginButton();
    await tboxWaitPage.waitForPageLoad();
    await webshopProductsChoiceTabPage.clickApparelShoesLink();
    await tboxWaitPage.waitForPageLoad();
    await webshopApparelShoesProductSelectionPage.clickBlueAndGreenSneakerLink();
    await tboxWaitPage.waitForPageLoad();
    capturedQuantityno = await webshopBlueJeansPage.getQuantityValue();
    capturedPrice = await webshopBlueJeansPage.getPrice();
    await webshopBlueJeansPage.clickAddToCartButton();
    await tboxWaitPage.waitForPageLoad();
    await webshopBlueJeansPage.clickShoppingCartLink();
    await tboxWaitPage.waitForPageLoad();
    await webshopShoppingCartPage.checkAgreeToTermsCheckbox();
    await webshopShoppingCartPage.clickCheckoutButton();
    await tboxWaitPage.waitForPageLoad();
    await webshopBillingAddressPage.clickContinueButton();
    await tboxWaitPage.waitForPageLoad();
    await webshopShippingAddressPage.clickContinueButton();
    await tboxWaitPage.waitForPageLoad();
    await webshopShippingMethodPage.clickGroundRadioButton();
    await webshopShippingMethodPage.clickContinueButton();
    await tboxWaitPage.waitForPageLoad();
    await webshopPaymentMethodsPage.clickCreditCardRadioButton();
    await webshopPaymentMethodsPage.clickContinueButton();
    await tboxWaitPage.waitForPageLoad();
    
    const currentDate = new Date();
    const expiryMonth = format(addMonths(currentDate, 6), 'MM');
    const expiryYear = format(addYears(currentDate, 2), 'yyyy');
    const cardNumber = faker.finance.creditCardNumber('####-####-####-####');
    const cvv = faker.finance.creditCardCVV();
    
    await webshopPaymentInformationCreditCardPage.selectCardType('Visa');
    await webshopPaymentInformationCreditCardPage.enterCardholderName(faker.person.fullName());
    await webshopPaymentInformationCreditCardPage.enterCardNumber(cardNumber);
    await webshopPaymentInformationCreditCardPage.selectExpirationMonth(expiryMonth);
    await webshopPaymentInformationCreditCardPage.selectExpirationYear(expiryYear);
    await webshopPaymentInformationCreditCardPage.enterCardCode(cvv);
    await webshopPaymentInformationCreditCardPage.clickContinueButton();
    await tboxWaitPage.waitForPageLoad();
    await webshopConfirmOrderPage.clickConfirmButton();
    await tboxWaitPage.waitForPageLoad();
    capturedOrderNumber = await webshopOrderSuccessfulPage.getOrderNumber();
    await webshopMyAccountNavigationPage.clickMyAccountLink();
    await tboxWaitPage.waitForPageLoad();
    await webshopMyAccountNavigationPage.clickOrdersLink();
    await tboxWaitPage.waitForPageLoad();
    await webshopMyAccountNavigationPage.clickDetailsButtonForOrder(capturedOrderNumber);
    await tboxWaitPage.waitForPageLoad();
    
    const orderDetailsQuantity = await webshopOrderDetailsPage.getOrderDetailsQuantity();
    const orderDetailsPrice = await webshopOrderDetailsPage.getOrderDetailsPrice();
    
    expect(orderDetailsQuantity).toBe(capturedQuantityno);
    expect(orderDetailsPrice).toBe(capturedPrice);
    
    await closebrowserPage.closeBrowser();
  });
});